### PR TITLE
introduce relative search window

### PR DESCRIPTION
**Pull request by robertnurnberg**
This PR introduces the possibility to define a search window relative to the eval of the root position. Also includes various cosmetic changes.

I believe this PR addresses https://github.com/vondele/chessgraph/issues/1.

PS: I am toying with the idea to use chessgraph to plot a daily graph for grobtrack, so there a relative search window would be very convenient.

Example outputs:
```shell
> python chessgraph.py --alpha 80 --beta 120 --relwin --depth 4 --san "1. g4 d5"
root position epd :  rnbqkbnr/ppp1pppp/8/3p4/6P1/8/PPPPPP1P/RNBQKBNR w KQkq - 0 2
eval              :  -122
alpha             :  -146
beta              :  -97
```
```shell
> python chessgraph.py --alpha 80 --beta 120 --relwin --depth 4 --san "1. e4 f5"
root position epd :  rnbqkbnr/ppppp1pp/8/5p2/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2
eval              :  161
alpha             :  128
beta              :  193
```

### CODE REVIEW

**Comment by vondele** [comment]
I think @dav1312 suggested something else, namely that the bounds change for each position in the tree (I guess in part to deal with the decay in cdb). That could be interesting, or could be messy (i.e. the window could drift), I can't really judge.

I wonder if it would not be better to give a window in cp rather than percentage of rootscore. This might be a bit more flexible (e.g. if the rootscore is 0). Also, my 2 cents, I think it is better not to repurpose the meaning of alpha/beta, but introduce new variables to express that relative window.

**Comment by robertnurnberg** [comment]
Yeah, I also thought about cp window, exactly because of rootscore 0. For automatic graphs for grob (eval can range from 96cp to 130cp these days), my gut feeling was that % may work more robustly.

We could offer both options? So window relative to rootscore in % and in cp? What would be good option names?
* `--ralpha` and `--rbeta` for relative alpha/beta for the effect of this PR
* `--salpha` and `--sbeta` for step (-defined) alpha/beta for the cp-defined window

What do you think?

**Comment by vondele** [comment]
yes, having the three options sounds good. Names sound find to me.

**Comment by robertnurnberg** [comment]
I have pushed the agreed changes. Sample outputs:

```
python chessgraph.py --ralpha 1.1 --rbeta 0.9 --depth 4 --san "1. g4 d5"
root position epd :  rnbqkbnr/ppp1pppp/8/3p4/6P1/8/PPPPPP1P/RNBQKBNR w KQkq - 0 2
eval              :  -122
alpha             :  -134
beta              :  -109
```
```
python chessgraph.py --ralpha 0.8 --rbeta 1.2 --depth 4 --san "1. e4 f5"
root position epd :  rnbqkbnr/ppppp1pp/8/5p2/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2
eval              :  161
alpha             :  128
beta              :  193
```
```
python chessgraph.py --salpha 5 --sbeta 10 --depth 4 --san "1. g4 d5"
root position epd :  rnbqkbnr/ppp1pppp/8/3p4/6P1/8/PPPPPP1P/RNBQKBNR w KQkq - 0 2
eval              :  -122
alpha             :  -127
beta              :  -112
```
```
python chessgraph.py --salpha 5 --sbeta 10 --depth 4 --san "1. e4 f5"
root position epd :  rnbqkbnr/ppppp1pp/8/5p2/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 2
eval              :  161
alpha             :  156
beta              :  171
```

I just noticed: it may make sense to switch the order in the print output to `alpha`, `eval`, `beta`? If you agree, I can push that change to this PR.

**Comment by vondele** [comment]
I think ideally sorted in the numerical order, so a wrong alpha beta window could be 
eval
alpha
beta

**Comment by robertnurnberg** [comment]
Hm, that's more code. With my suggestion (experienced) users can spot a non increasing order of numerical values as a sign of trouble?

**Comment by vondele** [comment]
fine to go with your original proposal as well.

**Comment by vondele** [comment]
is this ready for merging our you still want to reorder the output?

**Comment by robertnurnberg** [comment]
I have some more changes. Later this morning...

**Comment by robertnurnberg** [comment]
Updated the readme and added some more output. Examples:
```
python chessgraph.py --ralpha 1.1 --rbeta 0.9 --san "1. g4 d5"
root position epd :  rnbqkbnr/ppp1pppp/8/3p4/6P1/8/PPPPPP1P/RNBQKBNR w KQkq - 0 2
alpha             :  -134
eval              :  -122
beta              :  -109
depth             :  6
```
```
python chessgraph.py --ralpha 0.9 --rbeta 1.1 --san "1. g4 d5"
root position epd :  rnbqkbnr/ppp1pppp/8/3p4/6P1/8/PPPPPP1P/RNBQKBNR w KQkq - 0 2
alpha             :  -109  (alpha > eval!)
eval              :  -122
beta              :  -134  (beta < eval!)
depth             :  6
```

I think this is now ready to merge. I may add another PR on top of this with some more output for the user (concurrency, source, if cache gets reloaded). Just so that users who cannot be bothered to read the help know what is going on. ;)

**Pull request merged**
